apiVersion: v1
kind: Service
metadata:
  name: autofigure-edit
spec:
  type: NodePort
  selector:
    app: autofigure-edit
  ports:
    - name: http
      port: 31030
      targetPort: 8000
      nodePort: 31030
